.\" $OpenBSD$
.\" Copyright (c) 2023 Job Snijders <job@fastly.com>
.\"
.\" Permission to use, copy, modify, and distribute this software for any
.\" purpose with or without fee is hereby granted, provided that the above
.\" copyright notice and this permission notice appear in all copies.
.\"
.\" THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
.\" WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
.\" MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
.\" ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
.\" WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
.\" ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
.\" OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
.\"
.Dd $Mdocdate$
.Dt ROASORT 8
.Os
.Sh NAME
.Nm roasort
.Nd order and deduplicate ROA ip address information
.Sh DESCRIPTION
The
.Nm
utility reads a list of ROA IP address information elements from
.Em stdin ,
sorts and deduplicates the elements according to the canonicalization process
described in
.Em draft-ietf-sidrops-rfc6482bis .
.Sh EXIT STATUS
The
.Nm
utility exits 0 on success, and >0 if an error occurs,
such as the input containing duplicates or being unsorted.
.Sh EXAMPLES
.Bd -literal -offset indent
$ cat << EOF | ./roasort
10.0.0.0/24
10.0.0.0/24-24
10.0.0.0/8
2001:db8:db8::/48
2001:db8::/32
EOF
10.0.0.0/8
10.0.0.0/24
2001:db8::/32
2001:db8:db8::/48
$ echo $?
1

$ echo "2001:db8::/32\\n2001:db8::/48" | ./roasort
2001:db8::/32
2001:db8::/48
$ echo $?
0
.Ed
.Sh STANDARDS
.Rs
.%T A Profile for Route Origin Authorizations (ROAs)
.%U https://datatracker.ietf.org/doc/draft-ietf-sidrops-rfc6482bis/
.Re
.Sh AUTHORS
.An -nosplit
.An Job Snijders Aq Mt job@fastly.com
